version: "3.8"
services:
  client:
    env_file: ./client/.env
    environment:
      - ENV=${ENV}
      - USER_NAME=sharetech
      - APP_PATH=/sharetech/client
      - LANGUAGE=ja_JP:ja
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
      - WATCHPACK_POLLING=true
    build:
      context: .
      dockerfile: ./client/Dockerfile.${ENV}
      args:
        USER_NAME: root
        APP_PATH: /sharetech/client
    volumes:
      - ./:/sharetech
    working_dir: /sharetech/client
    command: /bin/sh -l
    tty: true
    stdin_open: true
    mem_limit: 2g
    ports:
      - 3030:3030

  sharetech-api:
    env_file: ./server/shareTech/.env
    environment:
      - ENV=${ENV}
      - USER_NAME=sharetech
      - APP_PATH=/sharetech/server/shareTech
      - LANGUAGE=ja_JP:ja
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    build:
      context: .
      dockerfile: ./server/shareTech/Dockerfile.${ENV}
      args:
        USER_NAME: root
        APP_PATH: /sharetech/server
    volumes:
      - ./:/sharetech
    working_dir: /sharetech/server
    command: /bin/sh -l
    tty: true
    stdin_open: true
    mem_limit: 2g
    ports:
      - 8080:8080
