version: "3.8"
services:
  client:
    env_file: ./client/.env
    environment:
      - ENV=${ENV}
      - USER_NAME=sharetech
      - APP_PATH=/sharetech/client
      - LANG=C.UTF-8
      - LANGUAGE='en_US:'
      - WATCHPACK_POLLING=true
    build:
      context: .
      dockerfile: ./client/Dockerfile.${ENV}
      args:
        USER_NAME: root
        APP_PATH: /sharetech/client
    volumes:
      - ./:/sharetech
    command: /bin/sh -l
    tty: true
    stdin_open: true
    mem_limit: 2g
    ports:
      - 3030:3030
  server:
    env_file: ./server/.env
    environment:
      - ENV=${ENV}
      - USER_NAME=sharetech
      - APP_PATH=/sharetech/server
      - LANG ja_JP.UTF-8
      - LANGUAGE ja_JP:ja
      - LC_ALL ja_JP.UTF-8
      - TZ JST-9
      - TERM xterm
    build:
      context: .
      dockerfile: ./server/Dockerfile.${ENV}
      args:
        USER_NAME: root
        APP_PATH: /sharetech/server
    volumes:
      - ./:/sharetech
    command: /bin/sh -l
    tty: true
    stdin_open: true
    mem_limit: 2g
    ports:
      - 8080:8080
