version: '3.8'
services:
  client:
    env_file: ./client/.env
    environment:
      - ENV=${ENV}
      - USER_NAME=sharetech
      - APP_PATH=/sharetech/client
      - LANG=C.UTF-8
      - LANGUAGE='en_US:'
      - WATCHPACK_POLLING=true
    build:
      context: .
      dockerfile: ./client/Dockerfile.${ENV}
      args:
        USER_NAME: root
        APP_PATH: /sharetech/client
    volumes:
      - ./:/sharetech
    command: /bin/sh -l
    tty: true
    stdin_open: true
    mem_limit: 2g
    ports:
      - 3030:3030
