from enum import Enum


class Roles(Enum):

    ORGANIZATION_ADMIN = "ORGANIZATION_ADMIN"
    ADMIN = "ADMIN"
    COLLABORATOR_EDITOR = "COLLABORATOR_EDITOR"
    COLLABORATOR_VIEWER = "COLLABORATOR_VIEWER"
