FROM python:3.8.10-slim

ARG USER_NAME
ARG APP_PATH
USER ${USER_NAME}
WORKDIR ${APP_PATH}

RUN apt update
RUN apt-get install -y git locales
RUN localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

RUN pip install --upgrade pip setuptools
RUN pip install pipenv

ENTRYPOINT ["./shareTech/entrypoint.sh"]
